apiVersion: v1
kind: Service
metadata:
  name: frontend-lb
  annotations:
    kubernetes.digitalocean.com/load-balancer-id: "frontend-load-balancer"
spec:
  type: LoadBalancer
  selector:
    app: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 4201
