name: build
on:
  workflow_call:
jobs:
  build:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16.14.0'
      - name: Install dependencies
        run: npm ci
      - name: Build project
        run: npm run build -- -c dev
