name: on-main-push
on: [pull_request]
jobs:
  build_main:
    uses: ./.github/workflows/build.yml

  create_image_main:
    needs: build_main
    uses: ./.github/workflows/create_image.yml
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}

  deploy_main:
    needs: create_image_main
    uses: ./.github/workflows/deploy.yml
    secrets:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      REGISTRY_NAME: ${{ secrets.REGISTRY_NAME }}
      CLUSTER_NAME: ${{ secrets.CLUSTER_NAME }}
